name: Simple Workflow 

on:
  push: 
    branches: 
      - main

jobs:
  print_message: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Print a message 
        run: echo "Hello, GitHub Actions!" 
